// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/TomSED/weather-api"
	"github.com/TomSED/weather-api/pkg/openweathermap"
	"sync"
)

var (
	lockOpenWeatherMapClientMockGetWeather sync.RWMutex
)

// Ensure, that OpenWeatherMapClientMock does implement weatherapi.OpenWeatherMapClient.
// If this is not the case, regenerate this file with moq.
var _ weatherapi.OpenWeatherMapClient = &OpenWeatherMapClientMock{}

// OpenWeatherMapClientMock is a mock implementation of weatherapi.OpenWeatherMapClient.
//
//     func TestSomethingThatUsesOpenWeatherMapClient(t *testing.T) {
//
//         // make and configure a mocked weatherapi.OpenWeatherMapClient
//         mockedOpenWeatherMapClient := &OpenWeatherMapClientMock{
//             GetWeatherFunc: func(city string) (*openweathermap.APIResponse, error) {
// 	               panic("mock out the GetWeather method")
//             },
//         }
//
//         // use mockedOpenWeatherMapClient in code that requires weatherapi.OpenWeatherMapClient
//         // and then make assertions.
//
//     }
type OpenWeatherMapClientMock struct {
	// GetWeatherFunc mocks the GetWeather method.
	GetWeatherFunc func(city string) (*openweathermap.APIResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetWeather holds details about calls to the GetWeather method.
		GetWeather []struct {
			// City is the city argument value.
			City string
		}
	}
}

// GetWeather calls GetWeatherFunc.
func (mock *OpenWeatherMapClientMock) GetWeather(city string) (*openweathermap.APIResponse, error) {
	if mock.GetWeatherFunc == nil {
		panic("OpenWeatherMapClientMock.GetWeatherFunc: method is nil but OpenWeatherMapClient.GetWeather was just called")
	}
	callInfo := struct {
		City string
	}{
		City: city,
	}
	lockOpenWeatherMapClientMockGetWeather.Lock()
	mock.calls.GetWeather = append(mock.calls.GetWeather, callInfo)
	lockOpenWeatherMapClientMockGetWeather.Unlock()
	return mock.GetWeatherFunc(city)
}

// GetWeatherCalls gets all the calls that were made to GetWeather.
// Check the length with:
//     len(mockedOpenWeatherMapClient.GetWeatherCalls())
func (mock *OpenWeatherMapClientMock) GetWeatherCalls() []struct {
	City string
} {
	var calls []struct {
		City string
	}
	lockOpenWeatherMapClientMockGetWeather.RLock()
	calls = mock.calls.GetWeather
	lockOpenWeatherMapClientMockGetWeather.RUnlock()
	return calls
}
